html/内部css反映ver
DaisukeMiyazaki/flask_sample_app pull request #1
Opened 2023-04-28 13:32 UTC by kanakof

大輔さん

Pullリクエスト承認お願いします。

2023-04-28 13:40 UTC, DaisukeMiyazaki requested changes
@kanakof 見ました！コメント確認よろしくお願いします！

2023-04-28 13:40 UTC, DaisukeMiyazaki commented on templates/page.html
> +      4. 自分と他人を比較しがちだ
@kanakof いい質問集だね！

2023-04-28 13:40 UTC, DaisukeMiyazaki commented on templates/page.html
> +
@kanakof これもいい質問だね！

2023-04-28 13:40 UTC, DaisukeMiyazaki commented on templates/page.html
> +    </style> -->
@kanakof これは外だししてください。これは、htmlのinlineを入れると可読性が下がったりするので、cssは別のファイルで用意することがベストプラクティスです。

参考はこちら、[static](https://stackoverflow.com/questions/20646822/how-to-serve-static-files-in-flask)で貼らないといけないです。

2023-04-28 13:40 UTC, kanakof commented on templates/page.html
> +    </style> -->
わかりました！対応します。

2023-04-29 08:02 UTC, kanakof commented
外部CSSに修正・変更しました！

2023-04-29 09:01 UTC, DaisukeMiyazaki approved these changes
@kanakof Looks good to me!

2023-04-29 09:08 UTC, DaisukeMiyazaki commented
@kanakof [a227001](https://github.com/DaisukeMiyazaki/flask_sample_app/pull/1/commits/a227001d0924dcccb4850a98494a8875f94342d4) ではベースcommitの後でのmain上での変更と当PRで変更箇所が被りすぎていてコンフリクトを起こしているため、解消しました。これでマージしてOKです！

2023-05-01 06:08 UTC, merged

2023-05-01 06:08 UTC, kanakof commented
確認ありがとうございました！